steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-sub-auto:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-sub-auto:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-sub-auto:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-sub-auto'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-sub-auto:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # Seoul region (or use your preferred region)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'  # Video rendering needs memory
      - '--cpu'
      - '4'    # More CPU for faster rendering
      - '--timeout'
      - '3600' # 60 minutes for long renders
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'    # Scale to zero when idle

images:
  - 'gcr.io/$PROJECT_ID/ai-sub-auto:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-sub-auto:latest'

options:
  machineType: 'E2_HIGHCPU_8'  # Faster builds
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'  # 30 minutes for build
